export const DAYS = ['mon', 'tue', 'wed', 'thu', 'fri'];
export const DAY_LABELS = { mon: '월', tue: '화', wed: '수', thu: '목', fri: '금' };
export const DAY_CLASSES = { mon: 'mon', tue: 'tue', wed: 'wed', thu: 'thu', fri: 'fri' };
export const CHILDREN = ['시우', '은우'];
export const START_MIN = 12 * 60;
export const END_MIN = 20 * 60;
export const SLOT_MIN = 10;
export const ROW_HEIGHT = 16;
export const PALETTE = ['#6C5CE7','#00A98F','#E05B3A','#C9348F','#0875D4','#B8870A','#0F8A7A','#A8265C','#2878BB','#5E50C0'];
